### ISSUE TITLE
help with configuration

### ISSUE THREAD

**Issue by rvzzz** [convexset/meteor-mathjax#1]
Hi, 
First of all thanks for the package. 
I need your help. I followed your configuration's steps and I can't make it work.
I tried inside: 
- Template.myTemplateName.onCreated();
- Template.myTemplateName.onRendered();

and in I ended up with: 

> ``` javascript
>        Meteor.startup(function() {
>             MathJaxHelper.useDefaultConfig();
>             MathJaxHelper.onMathJaxReady(function(MathJax) {
>                  // Warm Up the type setter
>                  var div = document.createElement('div');
>                  div.innerHTML = "$x$";
>                  MathJax.Hub.Queue(["Typeset", MathJax.Hub, div], function() {
>                      console.info("MathJax loaded.");
>                  });
>             });
>        });
> ```

Where should I put the configuration code?
Could you be gentle enough to provide me an example code of it here in a comment? 

Thank you, regards.

**Comment by convexset** [comment]
That block of code should be on the client (e.g.: some file in `/client/`) there's no need to put anything in template javascript.

In template HTML, `{{#mathjax}}{{mathContent}}{{/mathjax}}` will do (where `mathContent` is an appropriate helper).
